/**
 * demoSeed.ts — Generates realistic demo data for TraceLayer.
 *
 * NOTE: All integration data shown in the app is DEMO DATA generated by this seed.
 * In production, real API tokens would pull live data from connected apps.
 * This seed creates a complete project with sources, requirements, stakeholders,
 * decisions, conflicts, traceability links, agent logs, and a generated BRD document
 * to demonstrate the full TraceLayer pipeline workflow.
 */
import { v } from "convex/values";
import { mutation } from "./_generated/server";

// ─── Demo Source Content ─────────────────────────────────────────────────────
// Realistic multi-channel communication data as if pulled from integrations

const SLACK_MESSAGES = `#product-planning — Slack Export (TraceLayer Demo)

@sarah.chen [VP Engineering] — 2025-01-15 09:32 AM
Team, after reviewing Q4 metrics, we're moving forward with the customer portal redesign. The current portal has a 34% bounce rate and NPS of 2.1 — both unacceptable. We need a complete overhaul of the authentication flow, dashboard layout, and reporting module. Target launch is Q2. Budget approved for $2.4M.

@marcus.williams [Product Manager] — 2025-01-15 09:45 AM
Agreed. I've been collecting feedback from our top 50 enterprise clients. Key pain points:
1. SSO integration is broken for 60% of SAML providers
2. Dashboard load time averages 8.2 seconds (should be under 2s)
3. No mobile-responsive design — 38% of users access via mobile
4. Report generation takes 4-6 hours for large datasets
5. No real-time collaboration features
The competitor analysis shows Datadog and Grafana both offer sub-second dashboards. We're losing deals because of this.

@priya.patel [Security Lead] — 2025-01-15 10:02 AM
From a security standpoint, we MUST implement:
- SOC 2 Type II compliance (audit scheduled for July)
- End-to-end encryption for data at rest and in transit
- Role-based access control with minimum 5 permission levels
- MFA enforcement for all admin accounts
- GDPR and CCPA data residency controls
Non-negotiable. The board flagged this in the last review.

@david.kim [Frontend Lead] — 2025-01-15 10:18 AM
For the frontend, I'm proposing React 18 with Next.js 14. We'll use a micro-frontend architecture to allow independent team deployments. The design system will be built on Radix UI primitives with our custom theme tokens. Performance budget: LCP < 1.2s, FID < 50ms, CLS < 0.05. We'll need a dedicated performance engineer.

@sarah.chen — 2025-01-15 10:30 AM
All approved. @alex.thompson will lead the backend API redesign. We're moving from monolith to event-driven microservices. @priya.patel owns the security workstream. Let's set up weekly syncs starting next Monday.

@alex.thompson [Backend Architect] — 2025-01-15 11:15 AM
For the backend migration, I'm proposing:
- API Gateway: Kong or AWS API Gateway
- Event bus: Apache Kafka for async processing
- Database: PostgreSQL for transactional, Redis for caching, ClickHouse for analytics
- Auth: Keycloak for SSO/OIDC federation
- Container orchestration: Kubernetes on EKS
Estimated timeline: 14 weeks for MVP, 22 weeks for full migration. Need 3 additional senior engineers.

@lisa.nguyen [UX Research] — 2025-01-15 02:30 PM
Just finished the usability study with 25 participants. Key findings:
- 72% couldn't find the export function within 30 seconds
- Navigation was rated 2.8/5 for intuitiveness
- Users want drag-and-drop dashboard customization
- Dark mode was requested by 89% of participants
- Accessibility audit found 47 WCAG 2.1 AA violations
I'll share the full report with heat maps and session recordings by EOW.`;

const GITHUB_ISSUES = `GitHub Issues Export — customer-portal Repository (TraceLayer Demo)

Issue #342 — Performance: Dashboard API response time exceeds SLA
Status: Open | Priority: Critical | Labels: performance, backend, p0
Assigned: @alex.thompson
Created: 2025-01-10

The /api/v2/dashboard/metrics endpoint consistently takes 6-8 seconds for enterprise accounts with >10,000 data points. Root cause analysis shows N+1 query pattern in the aggregation pipeline. Current SLA requires < 500ms p95 response time.

Proposed fix: Implement materialized views with incremental refresh. Estimated effort: 2 sprints.

---

Issue #355 — Feature: Implement WebSocket-based real-time updates
Status: Open | Priority: High | Labels: feature, frontend, backend
Assigned: @david.kim
Created: 2025-01-12

Current polling interval of 30 seconds causes stale data display. Enterprise clients are reporting confusion when multiple team members edit simultaneously. Need real-time WebSocket connections for:
- Dashboard metric updates
- Collaborative editing (cursor presence, live changes)
- Alert notifications
- Pipeline status changes

Tech recommendation: Socket.io with Redis adapter for horizontal scaling.

---

Issue #361 — Security: SAML SSO failing for Okta and Azure AD
Status: Open | Priority: Critical | Labels: security, auth, p0
Assigned: @priya.patel
Created: 2025-01-14

60% of enterprise SSO configurations fail during SAML assertion validation. Root causes:
1. Clock skew tolerance too strict (< 30 seconds)
2. NameID format mismatch with some IdPs
3. Certificate rotation not handled gracefully
4. No support for encrypted assertions

This is blocking 12 enterprise onboardings worth $1.8M ARR.`;

const JIRA_EXPORT = `Jira Sprint Board Export — Portal Redesign (PORTAL) (TraceLayer Demo)

PORTAL-101 | Epic: Authentication Overhaul
Status: In Planning | Priority: Critical | Story Points: 34
Assignee: Alex Thompson | Sprint: Sprint 1-2
Description: Complete redesign of authentication system. Implement Keycloak-based SSO federation supporting SAML 2.0, OIDC, and LDAP. Must support MFA enforcement, session management, and role-based access control with custom permission sets.
Acceptance Criteria:
- Support 10+ SAML Identity Providers
- MFA via TOTP, WebAuthn, and SMS
- < 2 second authentication flow
- 99.99% auth service uptime SLA

PORTAL-115 | Epic: Dashboard Redesign
Status: Design Review | Priority: High | Story Points: 55
Assignee: David Kim | Sprint: Sprint 2-4
Description: Rebuild dashboard with real-time data visualization. Implement drag-and-drop widget system, custom layout persistence, and sub-second data rendering. Mobile-first responsive design.
Sub-tasks:
- PORTAL-116: Widget framework architecture
- PORTAL-117: Real-time data pipeline
- PORTAL-118: Mobile responsive layout
- PORTAL-119: Performance optimization (target: LCP < 1.2s)

PORTAL-130 | Epic: Reporting Engine V2
Status: Backlog | Priority: High | Story Points: 89
Assignee: Unassigned | Sprint: Sprint 4-6
Description: Replace batch reporting with streaming analytics engine. Target: generate 100-page reports in < 30 seconds (current: 4-6 hours). Support PDF, Excel, and interactive web formats. Implement scheduled and ad-hoc report generation.

PORTAL-142 | Story: API Rate Limiting and Throttling
Status: In Progress | Priority: Medium | Story Points: 8
Assignee: Alex Thompson | Sprint: Sprint 1
Description: Implement per-tenant API rate limiting using token bucket algorithm. Default: 1000 req/min for standard, 5000 req/min for enterprise. Include rate limit headers in all API responses. Add dashboard for tenants to monitor their usage.`;

const MEETING_TRANSCRIPT = `Meeting Transcript — "Portal Redesign Architecture Review" (TraceLayer Demo)
Date: 2025-01-16 | Duration: 67 minutes
Attendees: Sarah Chen (VP Eng), Alex Thompson (Backend), David Kim (Frontend), Priya Patel (Security), Marcus Williams (PM), James Rivera (DevOps)

[00:02:15] Sarah Chen: Let's go through the architecture proposal. Alex, walk us through the backend design.

[00:03:40] Alex Thompson: We're proposing a migration from the monolith to event-driven microservices. The core services will be: Auth Service, Dashboard Service, Analytics Service, Reporting Service, and Notification Service. Each service owns its data store. We'll use Kafka as the event bus for async communication between services.

[00:08:22] Sarah Chen: What's the migration strategy? We can't have downtime.

[00:09:15] Alex Thompson: Strangler fig pattern. We'll run both systems in parallel with a routing layer. Traffic will be gradually shifted service by service. Estimated 22 weeks for complete migration with zero downtime. Each service will have its own CI/CD pipeline.

[00:12:45] Priya Patel: I have security concerns with the microservices approach. Inter-service communication needs mTLS. We also need a centralized secret management solution — I'm recommending HashiCorp Vault. And every service must emit audit logs to our SIEM.

[00:15:30] Alex Thompson: Agreed on all points. We'll implement a service mesh using Istio for mTLS and observability. Vault for secrets. All audit events will flow through Kafka to the SIEM.

[00:18:20] David Kim: For the frontend, I want to clarify the micro-frontend approach. Each team will own a slice of the UI that deploys independently via Module Federation. The shell application handles routing, auth state, and shared design system components. This means the dashboard team can deploy daily without waiting for the auth team.

[00:22:00] Marcus Williams: Timeline check — can we hit Q2 launch? That's April 30th.

[00:22:45] Sarah Chen: Let's be realistic. MVP with auth and dashboard by April 30. Full feature set including reporting engine by June 30. We'll do a phased rollout: beta with 10 enterprise clients in May, general availability in July.

[00:25:10] James Rivera: DevOps perspective — we need to set up the Kubernetes clusters first. I need 3 weeks for infrastructure provisioning, CI/CD pipelines, and monitoring stack (Prometheus, Grafana, PagerDuty). After that, teams can start deploying services.

[00:28:00] Priya Patel: One more critical item — the SOC 2 Type II audit is scheduled for July 15. Every architectural decision must be documented for compliance. I need architecture decision records (ADRs) for each major choice.

[00:30:15] Sarah Chen: Decision: We proceed with the microservices architecture using Kubernetes and Kafka. Alex owns the backend architecture, David owns frontend, Priya owns security workstream, James owns infrastructure. MVP deadline: April 30. Budget: $2.4M approved. Weekly architecture review meetings continue.

[00:32:00] Marcus Williams: I'll create the project tracking in Jira and set up the sprint cadence. Two-week sprints, demos every other Friday. I'll also schedule the beta client communication for March to give them heads up.

[00:45:30] Alex Thompson: One concern — the reporting engine is significantly more complex than initially estimated. The streaming analytics pipeline for real-time reports needs careful design. I recommend we bring in a specialist contractor for the ClickHouse implementation.

[00:48:15] Sarah Chen: Approved. Marcus, add a contractor requisition to the budget. Up to $150K for a 6-month engagement.

[00:52:00] David Kim: For accessibility, Lisa's audit found 47 WCAG violations. I want to propose that we don't just fix existing violations but build the entire new UI to WCAG 2.2 AAA standard. It's more work upfront but prevents future remediation costs.

[00:54:30] Sarah Chen: I support AAA compliance. It's a differentiator in enterprise sales. Let's commit to that.

[00:60:00] Sarah Chen: Final decisions today: 1) Microservices with Kafka, 2) Kubernetes on EKS, 3) MVP by April 30, 4) Full launch by June 30, 5) WCAG 2.2 AAA, 6) SOC 2 compliance by July audit. Meeting adjourned.`;

const EMAIL_THREAD = `Email Thread — "RE: Customer Portal Redesign — Executive Sponsor Update" (TraceLayer Demo)

From: Sarah Chen <sarah.chen@company.com>
To: Robert Park <robert.park@company.com> (CTO)
CC: Marcus Williams <marcus.williams@company.com>
Date: 2025-01-17 08:15 AM
Subject: RE: Customer Portal Redesign — Executive Sponsor Update

Robert,

Following up on yesterday's architecture review. Key decisions:

1. Moving to microservices architecture (Kubernetes + Kafka)
2. New auth system with Keycloak — fixes the SAML/SSO issues blocking $1.8M in enterprise deals
3. Dashboard redesign targeting sub-second load times (currently 8.2s)
4. Full WCAG 2.2 AAA accessibility compliance
5. SOC 2 Type II readiness by July audit

Budget breakdown:
- Engineering headcount (12 engineers × 6 months): $1.8M
- Infrastructure (AWS EKS, Kafka, etc.): $200K
- Contractor (ClickHouse specialist): $150K
- Tooling and licenses: $100K
- Contingency (7%): $150K
Total: $2.4M (within approved budget)

Timeline:
- Sprint 1-2 (Jan 20 - Feb 14): Infrastructure, Auth Service MVP
- Sprint 3-4 (Feb 17 - Mar 14): Dashboard V2, SSO Integration
- Sprint 5-6 (Mar 17 - Apr 11): Reporting Engine, Mobile
- Sprint 7 (Apr 14 - Apr 30): MVP Launch prep, Beta
- Sprint 8-10 (May - Jun): Full feature set, GA prep

Risk items:
1. Reporting engine complexity — mitigated by specialist contractor
2. SOC 2 timeline tight — Priya starting documentation immediately
3. Migration rollback plan needed before production cutover

I'll send weekly status reports every Friday starting Jan 24.

Best,
Sarah

---
From: Robert Park <robert.park@company.com>
To: Sarah Chen <sarah.chen@company.com>
Date: 2025-01-17 09:30 AM

Sarah,

Excellent plan. The board is particularly interested in the SSO fix — Acme Corp and three other enterprise prospects are contingent on this. Please prioritize the auth workstream.

Two additions:
1. I want a customer-facing changelog and status page from day one. Transparency builds trust.
2. Consider implementing feature flags for the phased rollout. It gives us a kill switch if anything goes wrong.

Approved. Let's execute.

Robert`;

const CONFLUENCE_DOC = `Confluence Page — "Technical Requirements: Data Residency & GDPR Compliance" (TraceLayer Demo)
Space: Engineering | Author: Priya Patel | Last Updated: 2025-01-18

1. DATA RESIDENCY REQUIREMENTS

Enterprise customers require data residency guarantees:
- EU customers: Data must remain within EU-West (Frankfurt, Ireland)
- US customers: Data in US-East (Virginia) or US-West (Oregon)
- APAC customers: Singapore or Sydney
- Government: FedRAMP-authorized regions only

Implementation approach:
- Tenant-aware routing at the API Gateway level
- Region-specific Kubernetes clusters
- Cross-region replication ONLY for disaster recovery (encrypted, no PI data)
- Data classification labels on all database columns

2. GDPR COMPLIANCE

Required capabilities:
- Right to erasure (Article 17): Complete data deletion within 72 hours of request
- Data portability (Article 20): Export all user data in machine-readable format
- Consent management: Granular opt-in/opt-out for data processing categories
- Data Processing Agreements: Automated DPA generation for sub-processors
- Breach notification: Automated workflow to notify authorities within 72 hours

3. ENCRYPTION STANDARDS

- At rest: AES-256-GCM for all databases and file storage
- In transit: TLS 1.3 minimum, HSTS enabled
- Key management: AWS KMS with customer-managed keys (BYOK) option
- Certificate rotation: Automated via cert-manager, 90-day maximum validity

4. AUDIT LOGGING

All access to customer data must be logged:
- Who accessed what data, when, from where
- Immutable audit trail (append-only, 7-year retention)
- Real-time alerting on anomalous access patterns
- Quarterly access reviews for all engineering staff`;

// ─── Demo BRD Content ────────────────────────────────────────────────────────
const DEMO_BRD_CONTENT = {
  executiveSummary: `This Business Requirements Document (BRD) has been automatically generated by TraceLayer's Intelligence Engine from the analysis of 6 communication sources across 5 channels — including Slack conversations, GitHub issues, Jira sprint boards, meeting transcripts, email threads, and Confluence documentation. The extraction pipeline processed over 8,500 words of raw communication data, applying multi-layer intelligence including relevance filtering (94.2% average relevance score), stakeholder sentiment analysis, and conflict detection to produce this structured requirements document.

The Customer Portal Redesign project represents a strategic initiative to overhaul the company's client-facing portal, addressing critical issues around performance (current 8.2-second dashboard load times vs. the 2-second industry standard), security (60% SSO failure rate blocking $1.8M in enterprise deals), accessibility (47 WCAG 2.1 violations), and scalability. The approved budget of $2.4M covers a 22-week development cycle with a 12-person engineering team, transitioning from a monolithic architecture to event-driven microservices on Kubernetes.

TraceLayer's analysis identified 14 distinct requirements across functional, non-functional, security, and technical categories, with an average confidence score of 87.3%. The intelligence engine detected 2 potential conflicts between requirements — notably between the aggressive Q2 timeline and the scope of the reporting engine overhaul — and flagged them for stakeholder review. Six key stakeholders were identified with varying influence levels and sentiment patterns, providing a comprehensive view of organizational dynamics around this initiative.

The architectural decisions documented in this BRD — microservices migration, Kafka event bus, Keycloak authentication, and WCAG 2.2 AAA compliance — were extracted from actual team discussions and validated against the meeting transcript and email thread for accuracy. Each requirement is traced back to its source communication with an exact excerpt, enabling full explainability of how this BRD was constructed. The traceability matrix links 14 requirements to 6 sources, 6 stakeholders, and 8 decisions, forming a comprehensive knowledge graph.

This document serves as the authoritative specification for the Customer Portal Redesign, synthesized from real team communications rather than manually authored. It should be reviewed by all identified stakeholders, with particular attention to the flagged conflicts and the security requirements timeline relative to the July SOC 2 audit date.`,

  projectOverview: `The Customer Portal Redesign is a comprehensive initiative to rebuild the company's enterprise client-facing portal from the ground up. Triggered by declining user satisfaction metrics (NPS 2.1, 34% bounce rate) and competitive pressure from platforms like Datadog and Grafana that offer sub-second dashboard performance, this project addresses fundamental architectural limitations of the current monolithic system. The redesign encompasses authentication, real-time dashboards, reporting, security compliance, and mobile responsiveness.

The project follows a phased approach with an MVP launch targeted for April 30, 2025, covering authentication overhaul and dashboard redesign, followed by the full feature set including the streaming analytics reporting engine by June 30, 2025. A beta program with 10 enterprise clients will begin in May, with general availability in July — timed to coincide with the SOC 2 Type II audit. The total approved budget is $2.4M, with the largest allocation toward the 12-person engineering team over a 6-month development cycle.

The technical transformation involves migrating from a monolithic architecture to event-driven microservices using Kubernetes on AWS EKS, with Apache Kafka as the event bus. This architectural shift enables independent team deployments, improved fault isolation, and the horizontal scalability required for enterprise workloads. The migration will follow a strangler fig pattern to ensure zero downtime during the transition.`,

  businessObjectives: [
    {
      id: "OBJ-001",
      title: "Fix Enterprise SSO to Unblock Revenue",
      description: "Resolve the 60% SSO failure rate that is currently blocking 12 enterprise onboardings worth $1.8M ARR. Implement Keycloak-based SSO federation supporting SAML 2.0, OIDC, and LDAP with proper clock skew tolerance, NameID format handling, and encrypted assertion support. This is the highest-priority revenue-impacting issue identified across all communication channels.",
      successCriteria: "100% SSO compatibility with Okta, Azure AD, and OneLogin; Zero enterprise onboarding failures; < 2 second authentication flow",
      linkedRequirements: ["REQ-001", "REQ-002", "REQ-010"],
      metrics: "$1.8M ARR recovered within 60 days of launch; SSO success rate > 99.9%",
      owner: "Priya Patel",
    },
    {
      id: "OBJ-002",
      title: "Achieve Sub-Second Dashboard Performance",
      description: "Reduce dashboard load time from the current 8.2 seconds to under 1.2 seconds (LCP), matching or exceeding competitor benchmarks from Datadog and Grafana. This requires rebuilding the data pipeline with materialized views, implementing real-time WebSocket updates, and adopting a micro-frontend architecture for independent deployments.",
      successCriteria: "LCP < 1.2s, FID < 50ms, CLS < 0.05; Core Web Vitals all green; 50% reduction in bounce rate",
      linkedRequirements: ["REQ-003", "REQ-004", "REQ-006"],
      metrics: "Dashboard bounce rate < 17% (from 34%); User time-on-page +40%; NPS improvement to 4.0+",
      owner: "David Kim",
    },
    {
      id: "OBJ-003",
      title: "Achieve SOC 2 Type II Compliance",
      description: "Meet all SOC 2 Type II requirements before the scheduled audit on July 15, 2025. This encompasses end-to-end encryption, role-based access control, comprehensive audit logging, data residency controls, and GDPR compliance. Every architectural decision must be documented and auditable.",
      successCriteria: "Pass SOC 2 Type II audit on first attempt; Zero critical findings; Complete ADR documentation",
      linkedRequirements: ["REQ-002", "REQ-010", "REQ-011", "REQ-012", "REQ-013"],
      metrics: "Audit readiness score > 95%; Time to compliance documentation < 48 hours for any requirement",
      owner: "Priya Patel",
    },
    {
      id: "OBJ-004",
      title: "Launch Mobile-Responsive Enterprise Portal",
      description: "Address the 38% of users accessing the portal via mobile devices with a mobile-first responsive redesign. The new design will support all core functionality on tablets and smartphones, with touch-optimized interactions and offline capability for dashboard viewing.",
      successCriteria: "Full feature parity on mobile; Lighthouse mobile score > 90; Touch target compliance per WCAG 2.2 AAA",
      linkedRequirements: ["REQ-005", "REQ-014"],
      metrics: "Mobile user satisfaction > 4.0/5; Mobile session duration parity with desktop",
      owner: "David Kim",
    },
  ],

  scopeDefinition: {
    inScope: [
      "Authentication system overhaul with Keycloak SSO federation (SAML 2.0, OIDC, LDAP)",
      "Dashboard redesign with real-time data visualization and drag-and-drop customization",
      "Streaming analytics reporting engine (replacing batch processing)",
      "Mobile-responsive design (mobile-first approach)",
      "Microservices migration using strangler fig pattern",
      "SOC 2 Type II compliance and GDPR/CCPA data residency controls",
      "WCAG 2.2 AAA accessibility compliance",
      "Real-time collaboration features via WebSocket connections",
      "API rate limiting and throttling per tenant",
      "Customer-facing changelog and status page",
      "Feature flag system for phased rollout",
      "Dark mode UI theme (requested by 89% of users)",
    ],
    outOfScope: [
      "Native mobile applications (iOS/Android) — addressed in Phase 2",
      "Third-party marketplace or plugin ecosystem",
      "AI/ML-powered predictive analytics features",
      "Migration of historical report data older than 2 years",
      "Redesign of internal admin portal (separate initiative)",
    ],
    assumptions: [
      "AWS EKS infrastructure will be provisioned within 3 weeks",
      "3 additional senior engineers will be hired by Sprint 2",
      "ClickHouse specialist contractor can start by February 1",
      "Enterprise beta clients will be available for May testing",
      "Current API contracts remain backward-compatible during migration",
    ],
    constraints: [
      "SOC 2 Type II audit date: July 15, 2025 (non-negotiable)",
      "Total budget cap: $2.4M (approved by board)",
      "MVP must launch by April 30, 2025",
      "Zero downtime required during migration",
      "Must maintain backward compatibility with existing API consumers",
    ],
  },

  stakeholderAnalysis: `TraceLayer identified 6 key stakeholders from the analyzed communications, each with distinct roles, influence levels, and sentiment patterns. At the executive level, Sarah Chen (VP Engineering) serves as the primary decision-maker and project sponsor, demonstrating strongly supportive sentiment across all communications. She approved the $2.4M budget, set the Q2 timeline, and made final architectural decisions including the microservices migration and WCAG 2.2 AAA commitment. Robert Park (CTO) acts as the executive sponsor with board-level visibility, adding requirements for customer-facing transparency (changelog, status page) and feature flags for risk mitigation.

On the technical leadership front, Alex Thompson (Backend Architect) owns the backend architecture workstream and raised the critical concern about reporting engine complexity, leading to the contractor requisition decision. David Kim (Frontend Lead) drives the micro-frontend architecture and championed the WCAG 2.2 AAA upgrade from the initially identified AA standard. Priya Patel (Security Lead) owns the security workstream with non-negotiable requirements around SOC 2 compliance, encryption standards, and data residency — her sentiment is cautious but supportive, reflecting the tension between security rigor and timeline pressure.

Marcus Williams (Product Manager) bridges the business and technical teams, having conducted the enterprise client feedback study that quantified the SSO issue ($1.8M ARR impact) and performance gap. Lisa Nguyen (UX Research) provided critical usability data including the 47 WCAG violations and 89% dark mode request rate. James Rivera (DevOps) owns infrastructure provisioning with a clear 3-week setup timeline. The stakeholder network shows strong collaboration between engineering and security teams, with product serving as the voice of the customer throughout the decision-making process.`,

  functionalAnalysis: `The functional requirements landscape spans four major capability areas: Authentication & Access Control, Dashboard & Visualization, Reporting & Analytics, and Collaboration & Communication. Authentication (REQ-001, REQ-002) represents the most critical functional cluster, directly blocking $1.8M in enterprise revenue. The requirement for Keycloak-based SSO federation encompasses 10+ identity providers, multi-factor authentication (TOTP, WebAuthn, SMS), and session management — this is the highest-priority deliverable for Sprint 1-2.

Dashboard capabilities (REQ-003, REQ-004, REQ-005) form the second pillar, addressing the core user experience. The drag-and-drop widget system requires a flexible layout persistence mechanism and sub-second rendering through materialized views and WebSocket-based real-time updates. The mobile-responsive requirement adds complexity but addresses the 38% mobile user base. The micro-frontend architecture decision enables the dashboard team to deploy independently, which is critical for the aggressive timeline.

The Reporting Engine V2 (REQ-007) is the most technically complex functional requirement, estimated at 89 story points in the Jira backlog. The transition from 4-6 hour batch processing to 30-second streaming analytics requires a fundamentally different architecture using ClickHouse for the analytics data store. This requirement has a direct conflict with the Q2 timeline (flagged as CON-001) and prompted the decision to bring in a specialist contractor. The real-time collaboration features (REQ-006) via WebSocket connections address the stale data problem reported in GitHub Issue #355 and are essential for multi-user enterprise workflows.`,

  nonFunctionalAnalysis: `Non-functional requirements are dominated by Performance, Security, and Compliance categories, reflecting the enterprise nature of the customer portal. Performance requirements are specific and measurable: LCP < 1.2s, FID < 50ms, CLS < 0.05 for Core Web Vitals, with API response times under 500ms p95. These targets were benchmarked against competitors (Datadog, Grafana) and represent a significant improvement over current metrics. The materialized view approach for database optimization (addressing GitHub Issue #342) is the primary technical strategy for achieving these targets.

Security requirements (REQ-010, REQ-011, REQ-012, REQ-013) are the most stringently defined, driven by the July SOC 2 audit deadline and regulatory requirements. End-to-end encryption (AES-256-GCM at rest, TLS 1.3 in transit), role-based access control with 5+ permission levels, and immutable audit logging with 7-year retention form the security baseline. Data residency requirements add architectural complexity, requiring tenant-aware routing and region-specific clusters. The GDPR compliance requirements (right to erasure within 72 hours, data portability, consent management) require cross-cutting implementation across all microservices.

Accessibility and usability round out the non-functional landscape. The commitment to WCAG 2.2 AAA (upgraded from the initially identified AA level) is both a compliance requirement and a competitive differentiator for enterprise sales. The 47 existing violations identified in the usability study must be addressed, and new development must meet AAA standards from the outset. The 99.99% uptime SLA for the auth service sets critical reliability expectations for the infrastructure team.`,

  decisionAnalysis: `Eight key architectural and process decisions were extracted from the communications, each with clear ownership and rationale. The most significant is DEC-001: the adoption of microservices architecture with Kubernetes and Kafka, made by Sarah Chen with unanimous technical team support. This decision enables the independent deployment model, fault isolation, and horizontal scalability required for enterprise workloads, though it introduces operational complexity addressed by the dedicated DevOps workstream (James Rivera, 3-week infrastructure setup).

DEC-002 (Keycloak for authentication) and DEC-003 (micro-frontend architecture) address specific technical pain points. Keycloak was chosen for its comprehensive SSO federation support, directly resolving the SAML compatibility issues blocking enterprise onboarding. Module Federation for micro-frontends enables the aggressive timeline by allowing parallel team development. DEC-004 (strangler fig migration pattern) ensures zero-downtime migration — a non-negotiable constraint given the enterprise customer base.

The decision to pursue WCAG 2.2 AAA compliance (DEC-005) was a notable scope expansion championed by David Kim and approved by Sarah Chen, reflecting a strategic bet on accessibility as an enterprise differentiator. DEC-006 (specialist contractor for ClickHouse) demonstrates proactive risk mitigation for the reporting engine complexity identified by Alex Thompson. DEC-007 (phased rollout with feature flags) was added by Robert Park (CTO) as a risk control mechanism. DEC-008 (customer-facing changelog) reflects the executive emphasis on transparency. All decisions are documented as Architecture Decision Records (ADRs) for SOC 2 compliance.`,

  riskAssessment: `The intelligence engine identified two primary conflicts (CON-001, CON-002) and several additional risks from cross-referencing the extracted requirements. CON-001 — the timeline conflict between the reporting engine's 89-point complexity estimate and the Q2 deadline — is the highest-severity risk. The reporting engine alone requires an estimated 6 sprints (Sprints 4-6 per the project plan), but the streaming analytics architecture needs early design decisions that impact the overall system. The approved contractor engagement mitigates this but introduces a new risk around knowledge transfer and code ownership.

CON-002 — the tension between security requirements rigor and development velocity — manifests across multiple workstreams. The SOC 2 compliance requirement demands comprehensive documentation and audit trails that add overhead to every sprint. The data residency requirements (region-specific clusters, tenant-aware routing) add architectural complexity that could impact the infrastructure setup timeline. Mitigation: Priya Patel's early start on documentation and the security-by-design approach (building compliance into the architecture rather than retrofitting) reduce this risk.

Additional risks identified through cross-source analysis include: (1) Hiring risk — 3 additional senior engineers needed by Sprint 2, in a competitive market; (2) Technology risk — ClickHouse is a specialized technology requiring specific expertise; (3) Migration risk — strangler fig pattern requires careful traffic routing and monitoring; (4) Scope creep — the AAA accessibility upgrade and feature flag additions expand the original scope. Recommendations: Establish clear sprint-level scope locks, maintain a risk register with weekly reviews, and ensure the contingency budget (7%, $150K) is preserved for genuine contingencies rather than scope additions.`,

  intelligenceSummary: {
    totalSources: 6,
    communicationChannels: ["chat_log", "document", "email", "meeting_transcript"],
    totalRequirements: 14,
    totalStakeholders: 6,
    totalDecisions: 8,
    totalConflicts: 2,
    overallConfidence: 0.87,
    categoryBreakdown: "functional: 5, non_functional: 3, security: 3, technical: 2, performance: 1",
    priorityBreakdown: "critical: 4, high: 6, medium: 3, low: 1",
    summary: "TraceLayer processed 6 communication sources (8,500+ words) across Slack, GitHub, Jira, meeting transcripts, email, and Confluence. The intelligence engine extracted 14 requirements with 87.3% average confidence, identified 6 stakeholders with sentiment analysis, captured 8 architectural decisions, and detected 2 requirement conflicts. The traceability graph contains 47 links connecting sources → requirements → stakeholders → decisions."
  },

  confidenceReport: {
    highConfidence: 9,
    mediumConfidence: 4,
    lowConfidence: 1,
    overallScore: 0.87,
    coverageGaps: [
      "Limited data on API backward compatibility requirements — only mentioned in constraints, no detailed specification",
      "No explicit performance requirements for the reporting engine (only dashboard metrics specified)",
      "DevOps team infrastructure requirements beyond initial provisioning are underspecified",
      "Feature flag implementation details and governance process not yet defined",
    ],
    recommendations: [
      "Schedule dedicated requirements session for API backward compatibility with existing consumers",
      "Define specific SLAs for report generation times across different data volumes",
      "Establish infrastructure capacity planning and auto-scaling requirements for production",
      "Document feature flag lifecycle: creation, testing, rollout percentage, and cleanup policies",
      "Conduct security threat modeling session before architecture finalization",
    ],
  },
};

// ─── Demo Requirements ───────────────────────────────────────────────────────
const DEMO_REQUIREMENTS = [
  { id: "REQ-001", title: "SSO Federation with SAML 2.0, OIDC, and LDAP", desc: "Implement Keycloak-based Single Sign-On supporting 10+ identity providers including Okta, Azure AD, OneLogin, and custom SAML endpoints. Must handle clock skew tolerance, NameID format negotiation, encrypted assertions, and certificate rotation.", cat: "functional" as const, pri: "critical" as const, conf: 0.95, excerpt: "60% of enterprise SSO configurations fail during SAML assertion validation... blocking 12 enterprise onboardings worth $1.8M ARR", sourceIdx: 2 },
  { id: "REQ-002", title: "Multi-Factor Authentication Enforcement", desc: "Implement MFA enforcement for all admin accounts supporting TOTP, WebAuthn hardware keys, and SMS fallback. Include configurable MFA policies per tenant with grace periods and backup code generation.", cat: "security" as const, pri: "critical" as const, conf: 0.92, excerpt: "MFA enforcement for all admin accounts... Non-negotiable. The board flagged this in the last review.", sourceIdx: 0 },
  { id: "REQ-003", title: "Sub-Second Dashboard Performance (LCP < 1.2s)", desc: "Rebuild dashboard data pipeline to achieve Largest Contentful Paint under 1.2 seconds, First Input Delay under 50ms, and Cumulative Layout Shift under 0.05. Implement materialized views with incremental refresh for aggregation queries.", cat: "performance" as const, pri: "critical" as const, conf: 0.93, excerpt: "Performance budget: LCP < 1.2s, FID < 50ms, CLS < 0.05... dashboard load time averages 8.2 seconds", sourceIdx: 0 },
  { id: "REQ-004", title: "Drag-and-Drop Dashboard Widget System", desc: "Implement customizable dashboard with drag-and-drop widget placement, persistent layout configurations per user, and a library of pre-built visualization widgets. Support real-time data updates via WebSocket connections.", cat: "functional" as const, pri: "high" as const, conf: 0.88, excerpt: "Users want drag-and-drop dashboard customization... Dashboard load time averages 8.2 seconds", sourceIdx: 0 },
  { id: "REQ-005", title: "Mobile-First Responsive Design", desc: "Design and implement a fully responsive UI that provides feature parity across desktop, tablet, and mobile devices. 38% of current users access via mobile with no responsive support.", cat: "functional" as const, pri: "high" as const, conf: 0.90, excerpt: "No mobile-responsive design — 38% of users access via mobile", sourceIdx: 0 },
  { id: "REQ-006", title: "Real-Time Collaboration via WebSocket", desc: "Implement WebSocket-based real-time updates for dashboard metrics, collaborative editing with cursor presence, alert notifications, and pipeline status changes. Replace current 30-second polling with persistent connections.", cat: "functional" as const, pri: "high" as const, conf: 0.87, excerpt: "Current polling interval of 30 seconds causes stale data display... Need real-time WebSocket connections", sourceIdx: 1 },
  { id: "REQ-007", title: "Streaming Analytics Reporting Engine", desc: "Replace batch reporting system with streaming analytics engine. Target: generate 100-page reports in under 30 seconds (current: 4-6 hours). Support PDF, Excel, and interactive web formats with scheduled and ad-hoc generation.", cat: "functional" as const, pri: "high" as const, conf: 0.82, excerpt: "Replace batch reporting with streaming analytics engine. Target: generate 100-page reports in < 30 seconds", sourceIdx: 3 },
  { id: "REQ-008", title: "API Rate Limiting per Tenant", desc: "Implement per-tenant API rate limiting using token bucket algorithm. Default: 1000 req/min for standard tier, 5000 req/min for enterprise. Include rate limit headers in all API responses and a usage monitoring dashboard.", cat: "technical" as const, pri: "medium" as const, conf: 0.85, excerpt: "Implement per-tenant API rate limiting using token bucket algorithm", sourceIdx: 3 },
  { id: "REQ-009", title: "Microservices Migration via Strangler Fig Pattern", desc: "Migrate from monolithic architecture to event-driven microservices using Kubernetes on EKS with Kafka event bus. Use strangler fig pattern for zero-downtime migration. Core services: Auth, Dashboard, Analytics, Reporting, Notification.", cat: "technical" as const, pri: "critical" as const, conf: 0.94, excerpt: "Strangler fig pattern. We'll run both systems in parallel with a routing layer... zero downtime", sourceIdx: 4 },
  { id: "REQ-010", title: "Role-Based Access Control (5+ Levels)", desc: "Implement role-based access control with minimum 5 configurable permission levels. Support custom role definitions, permission inheritance, and tenant-scoped access policies. Mandatory for SOC 2 compliance.", cat: "security" as const, pri: "high" as const, conf: 0.91, excerpt: "Role-based access control with minimum 5 permission levels", sourceIdx: 0 },
  { id: "REQ-011", title: "End-to-End Encryption (AES-256 / TLS 1.3)", desc: "Implement AES-256-GCM encryption for all data at rest and TLS 1.3 minimum for data in transit. Key management via AWS KMS with customer-managed keys (BYOK) option. Automated certificate rotation with 90-day maximum validity.", cat: "security" as const, pri: "high" as const, conf: 0.93, excerpt: "AES-256-GCM for all databases and file storage... TLS 1.3 minimum, HSTS enabled", sourceIdx: 5 },
  { id: "REQ-012", title: "GDPR Data Residency & Right to Erasure", desc: "Implement tenant-aware data routing for EU, US, APAC, and FedRAMP regions. Support GDPR right to erasure within 72 hours, data portability in machine-readable format, and granular consent management.", cat: "compliance" as const, pri: "high" as const, conf: 0.89, excerpt: "Right to erasure... Complete data deletion within 72 hours... Data must remain within EU-West", sourceIdx: 5 },
  { id: "REQ-013", title: "Immutable Audit Logging (7-Year Retention)", desc: "Implement comprehensive audit logging for all data access events. Append-only immutable logs with 7-year retention. Real-time anomaly detection for suspicious access patterns. Quarterly automated access reviews.", cat: "compliance" as const, pri: "medium" as const, conf: 0.86, excerpt: "Immutable audit trail... 7-year retention... Real-time alerting on anomalous access patterns", sourceIdx: 5 },
  { id: "REQ-014", title: "WCAG 2.2 AAA Accessibility Compliance", desc: "Build the entire new UI to WCAG 2.2 AAA standard. Fix all 47 existing violations identified in the usability audit. Implement keyboard navigation, screen reader support, high contrast mode, and reduced motion preferences.", cat: "non_functional" as const, pri: "medium" as const, conf: 0.88, excerpt: "don't just fix existing violations but build the entire new UI to WCAG 2.2 AAA standard", sourceIdx: 4 },
];

// ─── Demo Stakeholders ───────────────────────────────────────────────────────
const DEMO_STAKEHOLDERS = [
  { name: "Sarah Chen", role: "VP Engineering", dept: "Engineering", influence: "decision_maker" as const, sentiment: "supportive" as const, mentions: 12 },
  { name: "Marcus Williams", role: "Product Manager", dept: "Product", influence: "influencer" as const, sentiment: "supportive" as const, mentions: 8 },
  { name: "Priya Patel", role: "Security Lead", dept: "Security", influence: "decision_maker" as const, sentiment: "neutral" as const, mentions: 9 },
  { name: "David Kim", role: "Frontend Lead", dept: "Engineering", influence: "influencer" as const, sentiment: "supportive" as const, mentions: 7 },
  { name: "Alex Thompson", role: "Backend Architect", dept: "Engineering", influence: "influencer" as const, sentiment: "supportive" as const, mentions: 8 },
  { name: "Robert Park", role: "CTO", dept: "Executive", influence: "decision_maker" as const, sentiment: "supportive" as const, mentions: 3 },
];

// ─── Demo Decisions ──────────────────────────────────────────────────────────
const DEMO_DECISIONS = [
  { id: "DEC-001", title: "Adopt Microservices Architecture with Kubernetes + Kafka", desc: "Migrate from monolith to event-driven microservices using Kubernetes on EKS with Apache Kafka as the event bus. Enables independent team deployments, fault isolation, and horizontal scalability.", type: "architectural", status: "approved" as const, conf: 0.95, excerpt: "We proceed with the microservices architecture using Kubernetes and Kafka", madeBy: 0 },
  { id: "DEC-002", title: "Keycloak for SSO Federation", desc: "Use Keycloak as the identity provider for SSO federation supporting SAML 2.0, OIDC, and LDAP protocols. Chosen for comprehensive IdP support and enterprise features.", type: "technical", status: "approved" as const, conf: 0.93, excerpt: "Auth: Keycloak for SSO/OIDC federation", madeBy: 4 },
  { id: "DEC-003", title: "Micro-Frontend Architecture via Module Federation", desc: "Adopt micro-frontend architecture using Webpack Module Federation. Each team owns and deploys a slice of the UI independently. Shell application handles routing and shared state.", type: "architectural", status: "approved" as const, conf: 0.90, excerpt: "Each team will own a slice of the UI that deploys independently via Module Federation", madeBy: 3 },
  { id: "DEC-004", title: "Strangler Fig Migration Pattern", desc: "Use strangler fig pattern for migration from monolith to microservices. Run both systems in parallel with a routing layer, gradually shifting traffic service by service. Ensures zero downtime.", type: "architectural", status: "approved" as const, conf: 0.92, excerpt: "Strangler fig pattern. We'll run both systems in parallel", madeBy: 4 },
  { id: "DEC-005", title: "WCAG 2.2 AAA Compliance (Upgraded from AA)", desc: "Commit to WCAG 2.2 AAA accessibility standard instead of the initially planned AA level. Strategic differentiator for enterprise sales. More work upfront but prevents future remediation costs.", type: "business", status: "approved" as const, conf: 0.88, excerpt: "build the entire new UI to WCAG 2.2 AAA standard", madeBy: 0 },
  { id: "DEC-006", title: "Hire ClickHouse Specialist Contractor", desc: "Engage a specialist contractor (up to $150K, 6-month engagement) for the ClickHouse implementation in the streaming analytics reporting engine. Mitigates technology risk.", type: "business", status: "approved" as const, conf: 0.91, excerpt: "Approved. Marcus, add a contractor requisition to the budget. Up to $150K", madeBy: 0 },
  { id: "DEC-007", title: "Feature Flags for Phased Rollout", desc: "Implement feature flag system for the phased rollout. Provides kill switch capability if issues arise during migration. Added by CTO as risk control mechanism.", type: "process", status: "approved" as const, conf: 0.87, excerpt: "Consider implementing feature flags for the phased rollout", madeBy: 5 },
  { id: "DEC-008", title: "Customer-Facing Changelog and Status Page", desc: "Launch a public changelog and status page from day one of the new portal. Transparency builds trust with enterprise customers during the transition period.", type: "business", status: "approved" as const, conf: 0.85, excerpt: "I want a customer-facing changelog and status page from day one", madeBy: 5 },
];

// ─── Seed Mutation ───────────────────────────────────────────────────────────
export const seedDemoProject = mutation({
  args: {},
  handler: async (ctx) => {
    const now = Date.now();

    // ── 1. Create project ─────────────────────────────────────────────────
    const projectId = await ctx.db.insert("projects", {
      name: "Customer Portal Redesign",
      description: "Complete overhaul of the enterprise customer portal — authentication, real-time dashboards, streaming analytics, and SOC 2 compliance. Extracted from 6 communication sources across Slack, GitHub, Jira, meeting transcripts, and email.",
      status: "active",
      outputFormat: "brd",
      color: "#6B7AE8",
      progress: 100,
      createdAt: now - 86400000 * 3,
      updatedAt: now,
      sourceCount: 6,
      requirementCount: 14,
      stakeholderCount: 6,
      decisionCount: 8,
      conflictCount: 2,
    });

    // ── 2. Create sources ─────────────────────────────────────────────────
    const sourceData: Array<{
      name: string;
      type: "chat_log" | "document" | "email" | "meeting_transcript";
      content: string;
      meta: { author?: string; channel?: string; subject?: string; participants?: string[]; wordCount: number; integrationAppId?: string };
    }> = [
      { name: "Slack — #product-planning", type: "chat_log", content: SLACK_MESSAGES, meta: { channel: "#product-planning", wordCount: 482, integrationAppId: "slack" } },
      { name: "GitHub Issues — customer-portal", type: "document", content: GITHUB_ISSUES, meta: { channel: "GitHub", wordCount: 318, integrationAppId: "github" } },
      { name: "Jira Sprint Board — PORTAL", type: "document", content: JIRA_EXPORT, meta: { channel: "Jira", wordCount: 290, integrationAppId: "jira" } },
      { name: "Meeting — Architecture Review (Jan 16)", type: "meeting_transcript", content: MEETING_TRANSCRIPT, meta: { participants: ["Sarah Chen", "Alex Thompson", "David Kim", "Priya Patel", "Marcus Williams", "James Rivera"], wordCount: 680 } },
      { name: "Email — Executive Sponsor Update", type: "email", content: EMAIL_THREAD, meta: { author: "Sarah Chen", subject: "RE: Customer Portal Redesign — Executive Sponsor Update", wordCount: 410, integrationAppId: "gmail" } },
      { name: "Confluence — Data Residency & GDPR", type: "document", content: CONFLUENCE_DOC, meta: { channel: "Confluence", wordCount: 320, integrationAppId: "confluence" } },
    ];

    const sourceIds: string[] = [];
    for (const src of sourceData) {
      const id = await ctx.db.insert("sources", {
        projectId,
        name: src.name,
        type: src.type,
        content: src.content,
        metadata: {
          author: src.meta.author,
          channel: src.meta.channel,
          subject: src.meta.subject,
          participants: src.meta.participants,
          wordCount: src.meta.wordCount,
          integrationAppId: src.meta.integrationAppId,
        },
        status: "extracted",
        relevanceScore: 0.94 + Math.random() * 0.06,
        createdAt: now - 86400000 * 2,
      });
      sourceIds.push(id);
    }

    // ── 3. Create stakeholders ────────────────────────────────────────────
    const stakeholderIds: string[] = [];
    for (const sh of DEMO_STAKEHOLDERS) {
      const id = await ctx.db.insert("stakeholders", {
        projectId,
        name: sh.name,
        role: sh.role,
        department: sh.dept,
        influence: sh.influence,
        sentiment: sh.sentiment,
        mentionCount: sh.mentions,
        sourceIds: sourceIds.map(s => s as any),
        relatedStakeholderIds: [],
        extractedAt: now - 86400000,
      });
      stakeholderIds.push(id);
    }

    // ── 4. Create requirements ────────────────────────────────────────────
    const requirementIds: string[] = [];
    for (const req of DEMO_REQUIREMENTS) {
      // Assign stakeholders based on relevance
      const assignedStakeholders = [];
      if (req.cat === "security" || req.cat === "compliance") assignedStakeholders.push(stakeholderIds[2]); // Priya
      if (req.cat === "functional" || req.cat === "performance") assignedStakeholders.push(stakeholderIds[3]); // David
      if (req.cat === "technical") assignedStakeholders.push(stakeholderIds[4]); // Alex
      assignedStakeholders.push(stakeholderIds[0]); // Sarah always involved

      const id = await ctx.db.insert("requirements", {
        projectId,
        requirementId: req.id,
        title: req.title,
        description: req.desc,
        category: req.cat,
        priority: req.pri,
        status: "confirmed",
        confidenceScore: req.conf,
        sourceId: sourceIds[req.sourceIdx] as any,
        sourceExcerpt: req.excerpt,
        stakeholderIds: assignedStakeholders as any[],
        linkedRequirementIds: [],
        linkedDecisionIds: [],
        extractedAt: now - 86400000,
        lastModified: now - 86400000,
        modifiedBy: "ai",
        extractionReasoning: `Extracted by TraceLayer Intelligence Engine with ${(req.conf * 100).toFixed(0)}% confidence. Source evidence directly quotes this requirement from ${sourceData[req.sourceIdx].name}.`,
        tags: [req.cat, req.pri],
      });
      requirementIds.push(id);
    }

    // ── 5. Create decisions ───────────────────────────────────────────────
    const decisionIds: string[] = [];
    for (const dec of DEMO_DECISIONS) {
      const id = await ctx.db.insert("decisions", {
        projectId,
        decisionId: dec.id,
        title: dec.title,
        description: dec.desc,
        type: dec.type,
        status: dec.status,
        madeBy: stakeholderIds[dec.madeBy] as any,
        sourceId: sourceIds[4] as any, // Most decisions from meeting/email
        sourceExcerpt: dec.excerpt,
        confidenceScore: dec.conf,
        impactedRequirementIds: [],
        extractedAt: now - 86400000,
      });
      decisionIds.push(id);
    }

    // ── 6. Create conflicts ───────────────────────────────────────────────
    await ctx.db.insert("conflicts", {
      projectId,
      conflictId: "CON-001",
      title: "Reporting Engine Complexity vs. Q2 Timeline",
      description: "The streaming analytics reporting engine (REQ-007, 89 story points) may not be achievable within the Q2 deadline. The ClickHouse implementation requires specialized expertise not currently on the team. | Risk mitigated by contractor engagement (DEC-006) but introduces knowledge transfer dependency.",
      severity: "major",
      status: "reviewing",
      requirementIds: [requirementIds[6], requirementIds[8]] as any[], // REQ-007 and REQ-009
      detectedAt: now - 86400000,
    });

    await ctx.db.insert("conflicts", {
      projectId,
      conflictId: "CON-002",
      title: "Security Compliance Rigor vs. Development Velocity",
      description: "SOC 2 Type II documentation requirements and security review gates may slow sprint velocity by 15-20%. Data residency requirements add architectural complexity to infrastructure setup timeline. | Mitigated by security-by-design approach and early documentation start.",
      severity: "minor",
      status: "reviewing",
      requirementIds: [requirementIds[9], requirementIds[11]] as any[], // REQ-010 and REQ-012
      detectedAt: now - 86400000,
    });

    // ── 7. Create traceability links ──────────────────────────────────────
    // Source → Requirement links
    for (let i = 0; i < DEMO_REQUIREMENTS.length; i++) {
      await ctx.db.insert("traceabilityLinks", {
        projectId,
        fromType: "requirement",
        fromId: requirementIds[i],
        toType: "source",
        toId: sourceIds[DEMO_REQUIREMENTS[i].sourceIdx],
        relationship: "extracted_from",
        strength: DEMO_REQUIREMENTS[i].conf,
        createdAt: now - 86400000,
      });
    }

    // Stakeholder → Source links
    for (let i = 0; i < stakeholderIds.length; i++) {
      for (const srcIdx of [0, 3, 4]) {
        await ctx.db.insert("traceabilityLinks", {
          projectId,
          fromType: "stakeholder",
          fromId: stakeholderIds[i],
          toType: "source",
          toId: sourceIds[srcIdx],
          relationship: "mentioned_in",
          strength: 0.8 + Math.random() * 0.2,
          createdAt: now - 86400000,
        });
      }
    }

    // Decision → Source links
    for (let i = 0; i < decisionIds.length; i++) {
      await ctx.db.insert("traceabilityLinks", {
        projectId,
        fromType: "decision",
        fromId: decisionIds[i],
        toType: "source",
        toId: sourceIds[4], // meeting transcript or email
        relationship: "decided_in",
        strength: DEMO_DECISIONS[i].conf,
        createdAt: now - 86400000,
      });
    }

    // Requirement → Stakeholder links
    for (let i = 0; i < requirementIds.length; i++) {
      const proposer = i < 3 ? stakeholderIds[0] : i < 6 ? stakeholderIds[3] : i < 9 ? stakeholderIds[4] : stakeholderIds[2];
      await ctx.db.insert("traceabilityLinks", {
        projectId,
        fromType: "requirement",
        fromId: requirementIds[i],
        toType: "stakeholder",
        toId: proposer,
        relationship: "proposed_by",
        strength: 0.85,
        createdAt: now - 86400000,
      });
    }

    // ── 8. Create BRD document ────────────────────────────────────────────
    await ctx.db.insert("documents", {
      projectId,
      type: "brd",
      version: 1,
      content: JSON.stringify(DEMO_BRD_CONTENT),
      generatedAt: now - 43200000,
      generatedFrom: {
        requirementCount: 14,
        sourceCount: 6,
        stakeholderCount: 6,
        decisionCount: 8,
      },
      status: "ready",
    });

    // ── 9. Create extraction run + agent logs ─────────────────────────────
    const runId = await ctx.db.insert("extractionRuns", {
      projectId,
      status: "completed",
      startedAt: now - 86400000 + 60000,
      completedAt: now - 86400000 + 180000,
      sourcesProcessed: 6,
      requirementsFound: 14,
      stakeholdersFound: 6,
      decisionsFound: 8,
      conflictsFound: 2,
    });

    // Generate realistic agent log entries
    const agentLogs = [
      { agent: "orchestrator", level: "info", msg: "🚀 Pipeline started — TraceLayer Intelligence Engine v1.0", t: 0 },
      { agent: "orchestrator", level: "info", msg: "Provider: GEMINI | Project: Customer Portal Redesign", t: 1000 },
      { agent: "ingestion_agent", level: "processing", msg: "📥 Found 6 source(s) to process", t: 2000 },
      { agent: "ingestion_agent", level: "success", msg: "  → Slack — #product-planning (chat_log, 482 words)", t: 3000 },
      { agent: "ingestion_agent", level: "success", msg: "  → GitHub Issues — customer-portal (document, 318 words)", t: 4000 },
      { agent: "ingestion_agent", level: "success", msg: "  → Jira Sprint Board — PORTAL (document, 290 words)", t: 5000 },
      { agent: "ingestion_agent", level: "success", msg: "  → Meeting — Architecture Review (meeting_transcript, 680 words)", t: 6000 },
      { agent: "ingestion_agent", level: "success", msg: "  → Email — Executive Sponsor Update (email, 410 words)", t: 7000 },
      { agent: "ingestion_agent", level: "success", msg: "  → Confluence — Data Residency & GDPR (document, 320 words)", t: 8000 },
      { agent: "ingestion_agent", level: "success", msg: "✅ Ingested 6 sources (2,500 total words)", t: 9000 },
      { agent: "classification_agent", level: "processing", msg: "🏷️ Classifying source relevance and type...", t: 12000 },
      { agent: "classification_agent", level: "success", msg: "  → 6/6 sources classified (avg relevance: 0.96)", t: 18000 },
      { agent: "requirement_agent", level: "processing", msg: "📋 Extracting requirements from 6 sources...", t: 20000 },
      { agent: "requirement_agent", level: "success", msg: "  → REQ-001: SSO Federation with SAML 2.0, OIDC, and LDAP [functional/critical] (95%)", t: 25000 },
      { agent: "requirement_agent", level: "success", msg: "  → REQ-002: Multi-Factor Authentication Enforcement [security/critical] (92%)", t: 27000 },
      { agent: "requirement_agent", level: "success", msg: "  → REQ-003: Sub-Second Dashboard Performance [performance/critical] (93%)", t: 29000 },
      { agent: "requirement_agent", level: "success", msg: "  → REQ-009: Microservices Migration via Strangler Fig [technical/critical] (94%)", t: 35000 },
      { agent: "requirement_agent", level: "success", msg: "✅ Extracted 14 requirements (avg confidence: 89.6%)", t: 45000 },
      { agent: "stakeholder_agent", level: "processing", msg: "👥 Identifying stakeholders and influence patterns...", t: 48000 },
      { agent: "stakeholder_agent", level: "success", msg: "  → Sarah Chen (VP Engineering) — decision_maker — supportive", t: 52000 },
      { agent: "stakeholder_agent", level: "success", msg: "  → Priya Patel (Security Lead) — decision_maker — neutral", t: 54000 },
      { agent: "stakeholder_agent", level: "success", msg: "  → Robert Park (CTO) — decision_maker — supportive", t: 56000 },
      { agent: "stakeholder_agent", level: "success", msg: "✅ Identified 6 stakeholders across 4 departments", t: 60000 },
      { agent: "decision_agent", level: "processing", msg: "🔑 Extracting decisions and approvals...", t: 62000 },
      { agent: "decision_agent", level: "success", msg: "  → DEC-001: Adopt Microservices Architecture [architectural] — approved", t: 68000 },
      { agent: "decision_agent", level: "success", msg: "  → DEC-002: Keycloak for SSO Federation [technical] — approved", t: 70000 },
      { agent: "decision_agent", level: "success", msg: "  → DEC-005: WCAG 2.2 AAA Compliance (upgraded) [business] — approved", t: 74000 },
      { agent: "decision_agent", level: "success", msg: "✅ Extracted 8 decisions (all approved by leadership)", t: 80000 },
      { agent: "timeline_agent", level: "processing", msg: "📅 Extracting timeline events and milestones...", t: 82000 },
      { agent: "timeline_agent", level: "success", msg: "  → milestone: MVP Launch (April 30, 2025)", t: 85000 },
      { agent: "timeline_agent", level: "success", msg: "  → deadline: SOC 2 Audit (July 15, 2025)", t: 86000 },
      { agent: "timeline_agent", level: "success", msg: "✅ Stored 6 timeline events", t: 90000 },
      { agent: "conflict_agent", level: "processing", msg: "⚡ Scanning for requirement conflicts...", t: 92000 },
      { agent: "conflict_agent", level: "warning", msg: "  ⚠️ MAJOR: Reporting Engine Complexity vs. Q2 Timeline — REQ-007 vs REQ-009", t: 98000 },
      { agent: "conflict_agent", level: "warning", msg: "  ⚠️ MINOR: Security Compliance Rigor vs. Development Velocity — REQ-010 vs REQ-012", t: 100000 },
      { agent: "traceability_agent", level: "processing", msg: "🔗 Building traceability graph...", t: 104000 },
      { agent: "traceability_agent", level: "success", msg: "✅ Traceability graph built — 14 requirements × 6 stakeholders, 47 links created", t: 112000 },
      { agent: "document_agent", level: "processing", msg: "📄 Generating BRD from structured intelligence...", t: 114000 },
      { agent: "document_agent", level: "success", msg: "✅ BRD generated successfully — 14 sections, 4,200 words", t: 125000 },
      { agent: "orchestrator", level: "success", msg: "🎉 Pipeline complete! 14 requirements, 6 stakeholders, 8 decisions, 2 conflicts extracted.", t: 128000 },
      { agent: "orchestrator", level: "info", msg: "📊 47 traceability links created. Knowledge graph ready.", t: 130000 },
    ];

    for (const log of agentLogs) {
      await ctx.db.insert("agentLogs", {
        projectId,
        extractionRunId: runId,
        agent: log.agent as any,
        level: log.level as any,
        message: log.msg,
        timestamp: now - 86400000 + 60000 + log.t,
      });
    }

    // ── 10. Create timeline events ────────────────────────────────────────
    await ctx.db.insert("timelineEvents", {
      projectId,
      title: "Infrastructure Provisioning Complete",
      description: "Kubernetes clusters, CI/CD pipelines, and monitoring stack (Prometheus, Grafana, PagerDuty) set up by James Rivera.",
      date: "2025-02-07",
      type: "milestone",
      sourceId: sourceIds[3] as any,
      confidenceScore: 0.88,
      extractedAt: now - 86400000,
    });
    await ctx.db.insert("timelineEvents", {
      projectId,
      title: "MVP Launch — Auth & Dashboard",
      description: "Minimum viable product with authentication overhaul and dashboard redesign. Target: April 30, 2025.",
      date: "2025-04-30",
      type: "deadline",
      sourceId: sourceIds[4] as any,
      confidenceScore: 0.95,
      extractedAt: now - 86400000,
    });
    await ctx.db.insert("timelineEvents", {
      projectId,
      title: "Beta Program with Enterprise Clients",
      description: "Phased rollout to 10 enterprise clients for validation and feedback.",
      date: "2025-05-15",
      type: "milestone",
      sourceId: sourceIds[4] as any,
      confidenceScore: 0.90,
      extractedAt: now - 86400000,
    });
    await ctx.db.insert("timelineEvents", {
      projectId,
      title: "Full Feature GA Release",
      description: "Complete feature set including streaming analytics reporting engine available to all customers.",
      date: "2025-06-30",
      type: "deadline",
      sourceId: sourceIds[3] as any,
      confidenceScore: 0.92,
      extractedAt: now - 86400000,
    });
    await ctx.db.insert("timelineEvents", {
      projectId,
      title: "SOC 2 Type II Audit",
      description: "Scheduled compliance audit. All architectural decisions and controls must be documented and auditable.",
      date: "2025-07-15",
      type: "deadline",
      sourceId: sourceIds[5] as any,
      confidenceScore: 0.97,
      extractedAt: now - 86400000,
    });
    await ctx.db.insert("timelineEvents", {
      projectId,
      title: "Budget Approval Decision",
      description: "$2.4M budget approved by board for complete portal redesign.",
      date: "2025-01-15",
      type: "approval",
      sourceId: sourceIds[0] as any,
      confidenceScore: 0.96,
      extractedAt: now - 86400000,
    });

    // ── 11. Create demo integrations ──────────────────────────────────────
    const demoIntegrations = [
      { appId: "slack", status: "connected" as const, items: 482, scope: { channels: ["#product-planning", "#engineering", "#security-alerts"] } },
      { appId: "github", status: "connected" as const, items: 318, scope: { repos: ["company/customer-portal", "company/auth-service"] } },
      { appId: "jira", status: "connected" as const, items: 290, scope: { projects: ["PORTAL", "AUTH"] } },
      { appId: "gmail", status: "connected" as const, items: 410, scope: { labels: ["Portal Redesign", "Architecture"] } },
      { appId: "confluence", status: "connected" as const, items: 320, scope: { pages: ["Engineering/Portal Redesign", "Security/Compliance"] } },
      { appId: "notion", status: "connected" as const, items: 156, scope: { pages: ["Product Roadmap", "Sprint Planning"] } },
    ];

    for (const integ of demoIntegrations) {
      await ctx.db.insert("integrations", {
        appId: integ.appId,
        status: integ.status,
        credentials: {
          tokenPreview: `demo-${integ.appId}-token...xxx`,
          scopes: ["read"],
          connectionMethod: "api_token",
        },
        dataScope: integ.scope as any,
        projectId,
        lastSyncAt: now - 3600000,
        lastSyncStatus: `Synced ${integ.items} items`,
        itemsSynced: integ.items,
        createdAt: now - 86400000 * 2,
        updatedAt: now - 3600000,
      });
    }

    return { success: true, projectId, message: "Demo project seeded with 6 sources, 14 requirements, 6 stakeholders, 8 decisions, 2 conflicts, full BRD, and 6 connected integrations." };
  },
});

// ─── Clear All Demo Data ─────────────────────────────────────────────────────
export const clearAllData = mutation({
  args: {},
  handler: async (ctx) => {
    const tables = [
      "projects", "sources", "requirements", "stakeholders", "decisions",
      "conflicts", "traceabilityLinks", "documents", "extractionRuns",
      "agentLogs", "timelineEvents", "integrations", "chatMessages",
    ] as const;

    let totalDeleted = 0;
    for (const table of tables) {
      const docs = await ctx.db.query(table).collect();
      for (const doc of docs) {
        await ctx.db.delete(doc._id);
        totalDeleted++;
      }
    }
    return { success: true, totalDeleted };
  },
});
