/**
 * ExportShareModal — Real export functionality for BRD documents.
 * Supports PDF (via print), Markdown (text download), and DOCX (XML blob).
 */
import { useState, useCallback } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "./ui/dialog";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "./ui/tabs";
import {
  FileText,
  File,
  FileCode,
  Copy,
  Mail,
  Lock,
  Check,
  Share2,
  Download,
  Loader2,
  CheckCircle2,
} from "lucide-react";
import { Button } from "./ui/button";

interface ExportShareModalProps {
  isOpen: boolean;
  onClose: () => void;
  projectName: string;
  version: number;
  projectId: string;
  brdContent: Record<string, any>;
  requirements: any[];
  stakeholders: any[];
  conflicts: any[];
  sources: any[];
}

// ─── Markdown Generator ─────────────────────────────────────────────────────
function generateMarkdown(
  projectName: string,
  version: number,
  brd: Record<string, any>,
  requirements: any[],
  stakeholders: any[],
  conflicts: any[],
  sources: any[]
): string {
  const lines: string[] = [];
  const add = (s: string) => lines.push(s);
  const blank = () => lines.push("");

  const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  // ─── Title Page ───────────────────────────────────────────────────────
  add(`# ${projectName}`);
  add(`## Business Requirements Document`);
  blank();
  add(`**Version:** ${version}.0 | **Generated:** ${date}`);
  add(`**Requirements:** ${requirements.length} | **Sources:** ${sources.length} | **Stakeholders:** ${stakeholders.length} | **Conflicts:** ${conflicts.length}`);
  blank();
  add(`*Generated by TraceLayer Intelligence Engine — automated multi-agent extraction pipeline*`);
  blank();
  add("---");
  blank();

  // ─── Table of Contents ────────────────────────────────────────────────
  add("## Table of Contents");
  blank();
  let sectionNum = 1;
  const toc: string[] = [];
  if (brd.executiveSummary) toc.push(`${sectionNum++}. [Executive Summary](#1-executive-summary)`);
  if (brd.projectOverview) toc.push(`${sectionNum++}. [Project Overview](#2-project-overview)`);
  if (brd.businessObjectives) toc.push(`${sectionNum++}. [Business Objectives](#3-business-objectives)`);
  if (brd.scopeDefinition) toc.push(`${sectionNum++}. [Scope Definition](#4-scope-definition)`);
  if (stakeholders.length > 0) toc.push(`${sectionNum++}. [Stakeholder Analysis](#5-stakeholder-analysis)`);
  if (brd.functionalAnalysis) toc.push(`${sectionNum++}. [Functional Analysis](#6-functional-analysis)`);
  if (requirements.length > 0) toc.push(`${sectionNum++}. [Requirements Specification](#7-requirements-specification)`);
  if (brd.nonFunctionalAnalysis) toc.push(`${sectionNum++}. [Non-Functional Analysis](#8-non-functional-analysis)`);
  if (brd.decisionAnalysis) toc.push(`${sectionNum++}. [Decision Analysis](#9-decision-analysis)`);
  if (brd.riskAssessment) toc.push(`${sectionNum++}. [Risk Assessment](#10-risk-assessment)`);
  if (conflicts.length > 0) toc.push(`${sectionNum++}. [Detected Conflicts](#11-detected-conflicts)`);
  if (brd.confidenceReport) toc.push(`${sectionNum++}. [Confidence Report](#12-confidence-report)`);
  toc.push(`${sectionNum++}. [Source Appendix](#source-appendix)`);
  toc.forEach((t) => add(t));
  blank();
  add("---");
  blank();

  // ─── Sections ─────────────────────────────────────────────────────────
  let sec = 1;

  if (brd.executiveSummary) {
    add(`## ${sec}. Executive Summary`);
    blank();
    add(brd.executiveSummary);
    blank();
    sec++;
  }

  if (brd.projectOverview) {
    add(`## ${sec}. Project Overview`);
    blank();
    add(brd.projectOverview);
    blank();
    sec++;
  }

  if (brd.businessObjectives) {
    add(`## ${sec}. Business Objectives`);
    blank();
    if (typeof brd.businessObjectives === "string") {
      add(brd.businessObjectives);
    } else if (Array.isArray(brd.businessObjectives)) {
      brd.businessObjectives.forEach((obj: any, i: number) => {
        add(`### ${sec}.${i + 1} ${obj.id || ""}: ${obj.title}`);
        blank();
        add(obj.description || "");
        if (obj.successCriteria) { blank(); add(`**Success Criteria:** ${obj.successCriteria}`); }
        if (obj.metrics) { add(`**Metrics:** ${obj.metrics}`); }
        if (obj.owner) { add(`**Owner:** ${obj.owner}`); }
        if (obj.linkedRequirements?.length) { add(`**Linked Requirements:** ${obj.linkedRequirements.join(", ")}`); }
        blank();
      });
    }
    sec++;
  }

  if (brd.scopeDefinition) {
    add(`## ${sec}. Scope Definition`);
    blank();
    const sd = brd.scopeDefinition;
    if (sd.inScope?.length) {
      add(`### ${sec}.1 In Scope`);
      sd.inScope.forEach((s: string) => add(`- ${s}`));
      blank();
    }
    if (sd.outOfScope?.length) {
      add(`### ${sec}.2 Out of Scope`);
      sd.outOfScope.forEach((s: string) => add(`- ${s}`));
      blank();
    }
    if (sd.assumptions?.length) {
      add(`### ${sec}.3 Assumptions`);
      sd.assumptions.forEach((s: string) => add(`- ${s}`));
      blank();
    }
    if (sd.constraints?.length) {
      add(`### ${sec}.4 Constraints`);
      sd.constraints.forEach((s: string) => add(`- ${s}`));
      blank();
    }
    sec++;
  }

  if (stakeholders.length > 0) {
    add(`## ${sec}. Stakeholder Analysis`);
    blank();
    if (brd.stakeholderAnalysis) {
      add(brd.stakeholderAnalysis);
      blank();
    }
    add("| # | Name | Role | Department | Influence | Sentiment |");
    add("|---|------|------|------------|-----------|-----------|");
    stakeholders.forEach((s: any, i: number) =>
      add(`| ${i + 1} | ${s.name} | ${s.role} | ${s.department || "—"} | ${s.influence} | ${s.sentiment || "—"} |`)
    );
    blank();
    sec++;
  }

  if (brd.functionalAnalysis) {
    add(`## ${sec}. Functional Analysis`);
    blank();
    add(brd.functionalAnalysis);
    blank();
    sec++;
  }

  if (requirements.length > 0) {
    add(`## ${sec}. Requirements Specification`);
    blank();
    add(`### ${sec}.1 Requirements Summary`);
    blank();
    add("| # | ID | Title | Priority | Category | Confidence |");
    add("|---|-----|-------|----------|----------|------------|");
    requirements.forEach((r: any, i: number) =>
      add(`| ${i + 1} | ${r.requirementId} | ${r.title} | ${r.priority} | ${r.category} | ${Math.round(r.confidenceScore * 100)}% |`)
    );
    blank();

    add(`### ${sec}.2 Detailed Requirements`);
    blank();
    requirements.forEach((r: any, i: number) => {
      add(`#### ${sec}.2.${i + 1} ${r.requirementId}: ${r.title}`);
      blank();
      add(`**Priority:** ${r.priority} | **Category:** ${r.category} | **Status:** ${r.status || "confirmed"} | **Confidence:** ${Math.round(r.confidenceScore * 100)}%`);
      blank();
      add(r.description || "No description.");
      blank();
      if (r.acceptanceCriteria?.length) {
        add("**Acceptance Criteria:**");
        r.acceptanceCriteria.forEach((ac: string) => add(`- ${ac}`));
        blank();
      }
      if (r.sourceExcerpt) {
        add(`> **Source Evidence:** "${r.sourceExcerpt}"`);
        blank();
      }
    });
    sec++;
  }

  if (brd.nonFunctionalAnalysis) {
    add(`## ${sec}. Non-Functional Analysis`);
    blank();
    add(brd.nonFunctionalAnalysis);
    blank();
    sec++;
  }

  if (brd.decisionAnalysis) {
    add(`## ${sec}. Decision Analysis`);
    blank();
    add(brd.decisionAnalysis);
    blank();
    sec++;
  }

  if (brd.riskAssessment) {
    add(`## ${sec}. Risk Assessment`);
    blank();
    add(brd.riskAssessment);
    blank();
    sec++;
  }

  if (conflicts.length > 0) {
    add(`## ${sec}. Detected Conflicts`);
    blank();
    conflicts.forEach((c: any, i: number) => {
      add(`### ${sec}.${i + 1} ${c.conflictId}: ${c.title} [${c.severity.toUpperCase()}]`);
      blank();
      add(`**Severity:** ${c.severity} | **Status:** ${c.status}`);
      blank();
      add(c.description);
      if (c.resolution) {
        blank();
        add(`**Resolution:** ${c.resolution}`);
      }
      blank();
    });
    sec++;
  }

  if (brd.confidenceReport) {
    add(`## ${sec}. Confidence Report`);
    blank();
    if (typeof brd.confidenceReport === "string") {
      add(brd.confidenceReport);
    } else {
      const cr = brd.confidenceReport;
      add(`**Overall Confidence Score:** ${Math.round((cr.overallScore || 0) * 100)}%`);
      blank();
      add(`| Confidence Level | Count |`);
      add(`|-----------------|-------|`);
      add(`| High (≥80%) | ${cr.highConfidence || 0} |`);
      add(`| Medium (50-79%) | ${cr.mediumConfidence || 0} |`);
      add(`| Low (<50%) | ${cr.lowConfidence || 0} |`);
      blank();
      if (cr.coverageGaps?.length) {
        add("**Coverage Gaps:**");
        cr.coverageGaps.forEach((g: string) => add(`- ${g}`));
        blank();
      }
      if (cr.recommendations?.length) {
        add("**Recommendations:**");
        cr.recommendations.forEach((r: string) => add(`- ${r}`));
        blank();
      }
    }
    sec++;
  }

  // ─── Source Appendix ──────────────────────────────────────────────────
  add("---");
  blank();
  add("## Source Appendix");
  blank();
  if (sources.length > 0) {
    add("| # | Source Name | Type | Words | Relevance |");
    add("|---|------------|------|-------|-----------|");
    sources.forEach((s: any, i: number) =>
      add(`| ${i + 1} | ${s.name} | ${s.type} | ${s.metadata?.wordCount || s.wordCount || 0} | ${s.relevanceScore ? Math.round(s.relevanceScore * 100) + "%" : "—"} |`)
    );
    blank();
  }

  add("---");
  blank();
  add(`*This document was automatically generated by TraceLayer Intelligence Engine on ${new Date().toLocaleString()}.*`);
  add(`*${requirements.length} requirements extracted from ${sources.length} sources with ${Math.round((brd.intelligenceSummary?.overallConfidence || 0.87) * 100)}% average confidence.*`);

  return lines.join("\n");
}

// ─── HTML Generator (for PDF printing) ──────────────────────────────────────
function generatePrintHTML(
  projectName: string,
  version: number,
  brd: Record<string, any>,
  requirements: any[],
  stakeholders: any[],
  conflicts: any[],
  sources: any[]
): string {
  const md = generateMarkdown(projectName, version, brd, requirements, stakeholders, conflicts, sources);

  let inTable = false;
  let tableHeaderDone = false;

  let html = md
    .replace(/^#### (.+)$/gm, "<h4>$1</h4>")
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/^## (.+)$/gm, (_, title) => {
      const anchor = title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/-+$/, "");
      return `<h2 id="${anchor}">${title}</h2>`;
    })
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    .replace(/^\*\*(.+?)\*\*$/gm, "<p><strong>$1</strong></p>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/^> (.+)$/gm, "<blockquote>$1</blockquote>")
    .replace(/^- (.+)$/gm, "<li>$1</li>")
    .replace(/^---$/gm, "<hr/>")
    .replace(/^\*(.+)\*$/gm, "<p><em>$1</em></p>");

  // Enhanced table handling with proper <th> for header rows
  const tableLines = html.split("\n");
  const processedLines: string[] = [];
  inTable = false;
  tableHeaderDone = false;

  for (let i = 0; i < tableLines.length; i++) {
    const line = tableLines[i].trim();
    if (line.startsWith("|") && line.endsWith("|")) {
      const cells = line.split("|").filter(Boolean).map(c => c.trim());

      // Separator row (|---|---|)
      if (cells.every(c => /^[-:]+$/.test(c))) {
        tableHeaderDone = true;
        continue;
      }

      if (!inTable) {
        processedLines.push('<table>');
        inTable = true;
        tableHeaderDone = false;
        // First row is header
        processedLines.push('<thead><tr>' + cells.map(c => `<th>${c}</th>`).join("") + '</tr></thead><tbody>');
        continue;
      }

      processedLines.push('<tr>' + cells.map(c => `<td>${c}</td>`).join("") + '</tr>');
    } else {
      if (inTable) {
        processedLines.push('</tbody></table>');
        inTable = false;
        tableHeaderDone = false;
      }
      processedLines.push(line);
    }
  }
  if (inTable) processedLines.push('</tbody></table>');

  html = processedLines.join("\n");
  html = html.replace(/(<li>.+<\/li>\n?)+/g, (m) => `<ul style="margin:8px 0;padding-left:20px;">${m}</ul>`);

  html = html
    .split("\n")
    .map((line) => {
      const trimmed = line.trim();
      if (!trimmed) return "";
      if (trimmed.startsWith("<")) return trimmed;
      return `<p style="margin:6px 0;line-height:1.7;color:#333;">${trimmed}</p>`;
    })
    .join("\n");

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>${projectName} — BRD v${version}</title>
  <style>
    @media print {
      @page { margin: 0.8in 0.75in; }
      .cover-page { page-break-after: always; }
      .toc-page { page-break-after: always; }
      h2 { page-break-before: always; }
      h2:first-of-type { page-break-before: avoid; }
      table { page-break-inside: avoid; }
    }
    * { box-sizing: border-box; }
    body {
      font-family: 'Inter', 'Segoe UI', system-ui, -apple-system, sans-serif;
      color: #1a1a1a; max-width: 850px; margin: 0 auto; padding: 40px;
      font-size: 13.5px; line-height: 1.7;
    }
    /* Cover page */
    .cover-page {
      display: flex; flex-direction: column; justify-content: center; align-items: center;
      min-height: 85vh; text-align: center; padding: 60px 20px;
    }
    .cover-page h1 { font-size: 32px; color: #111; border: none; margin: 0 0 8px; padding: 0; }
    .cover-page .subtitle { font-size: 18px; color: #4F5BD5; font-weight: 600; margin-bottom: 24px; }
    .cover-page .meta { font-size: 13px; color: #666; line-height: 1.8; }
    .cover-page .badge { display: inline-block; background: #4F5BD5; color: white; padding: 6px 18px; border-radius: 20px; font-size: 12px; font-weight: 600; margin-top: 24px; letter-spacing: 0.5px; }
    /* TOC */
    .toc-page { padding: 20px 0; }
    .toc-page h2 { font-size: 22px; color: #111; border-bottom: 2px solid #4F5BD5; padding-bottom: 8px; page-break-before: avoid; }
    .toc-item { display: flex; justify-content: space-between; padding: 6px 0; border-bottom: 1px dotted #ddd; font-size: 14px; }
    .toc-item a { color: #333; text-decoration: none; }
    .toc-item a:hover { color: #4F5BD5; }
    /* Content */
    h1 { font-size: 26px; margin-bottom: 8px; color: #111; border-bottom: 2px solid #4F5BD5; padding-bottom: 12px; }
    h2 { font-size: 20px; margin-top: 32px; color: #1a1a1a; border-bottom: 1px solid #ddd; padding-bottom: 8px; }
    h3 { font-size: 16px; margin-top: 20px; color: #333; }
    h4 { font-size: 14px; margin-top: 16px; color: #444; }
    blockquote { border-left: 3px solid #4F5BD5; padding: 10px 16px; margin: 14px 0; background: #FAFAF8; color: #555; font-size: 12.5px; border-radius: 0 4px 4px 0; }
    hr { border: none; border-top: 1px solid #e5e5e5; margin: 28px 0; }
    table { border-collapse: collapse; width: 100%; margin: 16px 0; font-size: 12.5px; }
    th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
    th { background: #F3F3EE; font-weight: 600; color: #333; }
    tr:nth-child(even) td { background: #FAFAF8; }
    code { background: #f0f0ec; padding: 2px 6px; border-radius: 3px; font-size: 12px; }
    .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #ddd; font-size: 11px; color: #999; text-align: center; }
  </style>
</head>
<body>
<!-- Cover Page -->
<div class="cover-page">
  <h1>${projectName}</h1>
  <div class="subtitle">Business Requirements Document</div>
  <div class="meta">
    Version ${version}.0<br/>
    Generated: ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}<br/>
    Requirements: ${requirements.length} | Sources: ${sources.length} | Stakeholders: ${stakeholders.length}
  </div>
  <div class="badge">TRACELAYER INTELLIGENCE ENGINE</div>
</div>

${html}

<div class="footer">
  Generated by TraceLayer Intelligence Engine &mdash; ${new Date().toLocaleString()}<br/>
  ${requirements.length} requirements extracted from ${sources.length} sources
</div>
</body>
</html>`;
}

// ─── DOCX Generator (Word 2003 XML) ────────────────────────────────────────
function generateDocxBlob(
  projectName: string,
  version: number,
  brd: Record<string, any>,
  requirements: any[],
  stakeholders: any[],
  conflicts: any[],
  sources: any[]
): Blob {
  const md = generateMarkdown(projectName, version, brd, requirements, stakeholders, conflicts, sources);
  const esc = (t: string) => t.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\*\*(.+?)\*\*/g, "$1");

  const xmlParts: string[] = [];
  const lines = md.split("\n");
  let i = 0;

  while (i < lines.length) {
    const trimmed = lines[i].trim();

    // Empty line
    if (!trimmed) {
      xmlParts.push('<w:p><w:r><w:t></w:t></w:r></w:p>');
      i++;
      continue;
    }

    // Table block — collect contiguous | lines
    if (trimmed.startsWith("|")) {
      const tableRows: string[][] = [];
      while (i < lines.length && lines[i].trim().startsWith("|")) {
        const row = lines[i].trim();
        const cells = row.split("|").filter(Boolean).map(c => c.trim());
        // Skip separator row
        if (!cells.every(c => /^[-:]+$/.test(c))) {
          tableRows.push(cells);
        }
        i++;
      }
      if (tableRows.length > 0) {
        const colCount = tableRows[0].length;
        const colW = Math.floor(9000 / colCount);
        let tblXml = '<w:tbl><w:tblPr><w:tblBorders>';
        tblXml += '<w:top w:val="single" w:sz="4" w:space="0" w:color="CCCCCC"/>';
        tblXml += '<w:left w:val="single" w:sz="4" w:space="0" w:color="CCCCCC"/>';
        tblXml += '<w:bottom w:val="single" w:sz="4" w:space="0" w:color="CCCCCC"/>';
        tblXml += '<w:right w:val="single" w:sz="4" w:space="0" w:color="CCCCCC"/>';
        tblXml += '<w:insideH w:val="single" w:sz="4" w:space="0" w:color="CCCCCC"/>';
        tblXml += '<w:insideV w:val="single" w:sz="4" w:space="0" w:color="CCCCCC"/>';
        tblXml += '</w:tblBorders></w:tblPr>';

        // Grid
        tblXml += '<w:tblGrid>' + Array(colCount).fill(`<w:gridCol w:w="${colW}"/>`).join("") + '</w:tblGrid>';

        tableRows.forEach((row, ri) => {
          tblXml += '<w:tr>';
          row.forEach(cell => {
            const boldRpr = ri === 0 ? '<w:b/><w:sz w:val="20"/>' : '<w:sz w:val="20"/>';
            const shading = ri === 0 ? '<w:shd w:val="clear" w:color="auto" w:fill="F3F3EE"/>' : '';
            tblXml += `<w:tc><w:tcPr><w:tcW w:w="${colW}" w:type="dxa"/>${shading}</w:tcPr>`;
            tblXml += `<w:p><w:r><w:rPr>${boldRpr}</w:rPr><w:t xml:space="preserve">${esc(cell)}</w:t></w:r></w:p></w:tc>`;
          });
          tblXml += '</w:tr>';
        });
        tblXml += '</w:tbl>';
        xmlParts.push(tblXml);
      }
      continue;
    }

    // Headings
    let style = "Normal";
    let text = trimmed;
    let bold = false;

    if (trimmed.startsWith("#### ")) { style = "Heading4"; text = trimmed.slice(5); }
    else if (trimmed.startsWith("### ")) { style = "Heading3"; text = trimmed.slice(4); }
    else if (trimmed.startsWith("## ")) { style = "Heading2"; text = trimmed.slice(3); }
    else if (trimmed.startsWith("# ")) { style = "Heading1"; text = trimmed.slice(2); }
    else if (trimmed.startsWith("- ")) { style = "ListBullet"; text = trimmed.slice(2); }
    else if (trimmed.startsWith("> ")) { text = trimmed.slice(2); }
    else if (trimmed.startsWith("**") && trimmed.endsWith("**")) { bold = true; text = trimmed.slice(2, -2); }
    else if (trimmed === "---") {
      xmlParts.push('<w:p><w:pPr><w:pBdr><w:bottom w:val="single" w:sz="4" w:space="1" w:color="CCCCCC"/></w:pBdr></w:pPr></w:p>');
      i++;
      continue;
    }

    const boldXml = bold ? "<w:b/>" : "";
    xmlParts.push(`<w:p><w:pPr><w:pStyle w:val="${style}"/></w:pPr><w:r><w:rPr>${boldXml}</w:rPr><w:t xml:space="preserve">${esc(text)}</w:t></w:r></w:p>`);
    i++;
  }

  const wordXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?mso-application progid="Word.Document"?>
<w:wordDocument xmlns:w="http://schemas.microsoft.com/office/word/2003/wordml"
  xmlns:wx="http://schemas.microsoft.com/office/word/2003/auxHint">
  <w:styles>
    <w:style w:type="paragraph" w:styleId="Heading1">
      <w:name w:val="heading 1"/>
      <w:pPr><w:spacing w:before="360" w:after="120"/><w:pBdr><w:bottom w:val="single" w:sz="6" w:space="4" w:color="4F5BD5"/></w:pBdr></w:pPr>
      <w:rPr><w:b/><w:sz w:val="52"/><w:color w:val="111111"/></w:rPr>
    </w:style>
    <w:style w:type="paragraph" w:styleId="Heading2">
      <w:name w:val="heading 2"/>
      <w:pPr><w:spacing w:before="280" w:after="100"/><w:pBdr><w:bottom w:val="single" w:sz="4" w:space="3" w:color="DDDDDD"/></w:pBdr></w:pPr>
      <w:rPr><w:b/><w:sz w:val="40"/><w:color w:val="1A1A1A"/></w:rPr>
    </w:style>
    <w:style w:type="paragraph" w:styleId="Heading3">
      <w:name w:val="heading 3"/>
      <w:pPr><w:spacing w:before="200" w:after="80"/></w:pPr>
      <w:rPr><w:b/><w:sz w:val="32"/><w:color w:val="333333"/></w:rPr>
    </w:style>
    <w:style w:type="paragraph" w:styleId="Heading4">
      <w:name w:val="heading 4"/>
      <w:pPr><w:spacing w:before="160" w:after="60"/></w:pPr>
      <w:rPr><w:b/><w:sz w:val="28"/><w:color w:val="444444"/></w:rPr>
    </w:style>
    <w:style w:type="paragraph" w:styleId="Normal">
      <w:name w:val="Normal"/>
      <w:pPr><w:spacing w:after="60" w:line="360" w:lineRule="auto"/></w:pPr>
      <w:rPr><w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/><w:sz w:val="22"/><w:color w:val="1A1A1A"/></w:rPr>
    </w:style>
    <w:style w:type="paragraph" w:styleId="ListBullet">
      <w:name w:val="List Bullet"/>
      <w:pPr><w:spacing w:after="40"/><w:ind w:left="720" w:hanging="360"/></w:pPr>
      <w:rPr><w:sz w:val="22"/></w:rPr>
    </w:style>
  </w:styles>
  <w:body>
    ${xmlParts.join("\n")}
  </w:body>
</w:wordDocument>`;

  return new Blob([wordXml], { type: "application/vnd.ms-word" });
}

// ─── Download helper ─────────────────────────────────────────────────────────
function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ─── Component ───────────────────────────────────────────────────────────────
export function ExportShareModal({
  isOpen,
  onClose,
  projectName,
  version,
  projectId,
  brdContent,
  requirements,
  stakeholders,
  conflicts,
  sources,
}: ExportShareModalProps) {
  const [copied, setCopied] = useState(false);
  const [exporting, setExporting] = useState<string | null>(null);
  const [exported, setExported] = useState<string | null>(null);

  const safeName = projectName.replace(/[^a-zA-Z0-9_-]/g, "_");

  const handleExportPDF = useCallback(() => {
    setExporting("pdf");
    try {
      const html = generatePrintHTML(projectName, version, brdContent, requirements, stakeholders, conflicts, sources);
      const printWindow = window.open("", "_blank");
      if (printWindow) {
        printWindow.document.write(html);
        printWindow.document.close();
        setTimeout(() => {
          printWindow.print();
          setExported("pdf");
        }, 500);
      }
    } catch (e) {
      console.error("PDF export failed:", e);
    } finally {
      setExporting(null);
      setTimeout(() => setExported(null), 3000);
    }
  }, [projectName, version, brdContent, requirements, stakeholders, conflicts, sources]);

  const handleExportMarkdown = useCallback(() => {
    setExporting("md");
    try {
      const md = generateMarkdown(projectName, version, brdContent, requirements, stakeholders, conflicts, sources);
      const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
      downloadBlob(blob, `${safeName}_BRD_v${version}.md`);
      setExported("md");
    } catch (e) {
      console.error("Markdown export failed:", e);
    } finally {
      setExporting(null);
      setTimeout(() => setExported(null), 3000);
    }
  }, [projectName, version, brdContent, requirements, stakeholders, conflicts, sources, safeName]);

  const handleExportDocx = useCallback(() => {
    setExporting("docx");
    try {
      const blob = generateDocxBlob(projectName, version, brdContent, requirements, stakeholders, conflicts, sources);
      downloadBlob(blob, `${safeName}_BRD_v${version}.doc`);
      setExported("docx");
    } catch (e) {
      console.error("DOCX export failed:", e);
    } finally {
      setExporting(null);
      setTimeout(() => setExported(null), 3000);
    }
  }, [projectName, version, brdContent, requirements, stakeholders, conflicts, sources, safeName]);

  const handleCopy = () => {
    const md = generateMarkdown(projectName, version, brdContent, requirements, stakeholders, conflicts, sources);
    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="sm:max-w-[600px] p-0 gap-0 bg-background border-border/50 overflow-hidden rounded-2xl shadow-xl">
        <DialogHeader className="px-6 pt-6 pb-4">
          <DialogTitle className="text-xl font-semibold text-foreground">Export & Share</DialogTitle>
          <DialogDescription className="text-sm text-muted-foreground mt-1">
            {projectName} BRD v{version}.0 — {requirements.length} requirements, {sources.length} sources
          </DialogDescription>
        </DialogHeader>

        <Tabs defaultValue="download" className="w-full flex flex-col gap-0">
          <div className="px-6 pb-2">
            <TabsList className="w-full h-12 bg-transparent p-0 gap-4 justify-start">
              <TabsTrigger
                value="download"
                className="flex-1 data-[state=active]:border-primary data-[state=active]:text-primary data-[state=active]:bg-transparent border border-transparent text-muted-foreground h-full rounded-lg px-8 shadow-none data-[state=active]:shadow-none"
              >
                <Download className="w-4 h-4 mr-2" />
                Download
              </TabsTrigger>
              <TabsTrigger
                value="share"
                className="flex-1 data-[state=active]:border-primary data-[state=active]:text-primary data-[state=active]:bg-transparent border border-transparent text-muted-foreground h-full rounded-lg px-8 shadow-none data-[state=active]:shadow-none"
              >
                <Share2 className="w-4 h-4 mr-2" />
                Share
              </TabsTrigger>
            </TabsList>
          </div>

          <TabsContent value="download" className="p-6 m-0 space-y-6">
            <div className="grid grid-cols-3 gap-4">
              <button
                onClick={handleExportPDF}
                disabled={exporting === "pdf"}
                className="flex flex-col items-center justify-center gap-3 p-5 rounded-2xl border border-border/60 bg-card hover:bg-muted/30 hover:border-primary/30 transition-all group shadow-sm disabled:opacity-60"
              >
                <div className="w-12 h-12 rounded-xl bg-rose-50 text-rose-500 flex items-center justify-center group-hover:scale-110 transition-transform">
                  {exporting === "pdf" ? <Loader2 className="w-6 h-6 animate-spin" /> :
                    exported === "pdf" ? <CheckCircle2 className="w-6 h-6 text-emerald-500" /> :
                      <FileText className="w-6 h-6" />}
                </div>
                <div className="text-center">
                  <div className="text-sm font-medium text-foreground">PDF</div>
                  <div className="text-[11px] text-muted-foreground mt-0.5">Print to PDF</div>
                </div>
              </button>

              <button
                onClick={handleExportDocx}
                disabled={exporting === "docx"}
                className="flex flex-col items-center justify-center gap-3 p-5 rounded-2xl border border-border/60 bg-card hover:bg-muted/30 hover:border-primary/30 transition-all group shadow-sm disabled:opacity-60"
              >
                <div className="w-12 h-12 rounded-xl bg-blue-50 text-blue-500 flex items-center justify-center group-hover:scale-110 transition-transform">
                  {exporting === "docx" ? <Loader2 className="w-6 h-6 animate-spin" /> :
                    exported === "docx" ? <CheckCircle2 className="w-6 h-6 text-emerald-500" /> :
                      <File className="w-6 h-6" />}
                </div>
                <div className="text-center">
                  <div className="text-sm font-medium text-foreground">Word</div>
                  <div className="text-[11px] text-muted-foreground mt-0.5">Editable .doc</div>
                </div>
              </button>

              <button
                onClick={handleExportMarkdown}
                disabled={exporting === "md"}
                className="flex flex-col items-center justify-center gap-3 p-5 rounded-2xl border border-border/60 bg-card hover:bg-muted/30 hover:border-primary/30 transition-all group shadow-sm disabled:opacity-60"
              >
                <div className="w-12 h-12 rounded-xl bg-muted text-muted-foreground flex items-center justify-center group-hover:scale-110 transition-transform">
                  {exporting === "md" ? <Loader2 className="w-6 h-6 animate-spin" /> :
                    exported === "md" ? <CheckCircle2 className="w-6 h-6 text-emerald-500" /> :
                      <FileCode className="w-6 h-6" />}
                </div>
                <div className="text-center">
                  <div className="text-sm font-medium text-foreground">Markdown</div>
                  <div className="text-[11px] text-muted-foreground mt-0.5">Raw .md file</div>
                </div>
              </button>
            </div>

            <div className="bg-muted/40 rounded-xl p-4">
              <p className="text-[12px] font-medium text-muted-foreground mb-2">Export includes:</p>
              <div className="flex flex-wrap gap-2">
                {["Executive Summary", "Scope", "Stakeholders", `${requirements.length} Requirements`, "Risk Assessment",
                  conflicts.length > 0 ? `${conflicts.length} Conflicts` : null, "Traceability", "Confidence Report"
                ].filter(Boolean).map((item) => (
                  <span key={item} className="text-[11px] px-2 py-1 rounded-lg bg-card border border-border/40 text-foreground/70">
                    {item}
                  </span>
                ))}
              </div>
            </div>
          </TabsContent>

          <TabsContent value="share" className="p-6 m-0 space-y-6">
            <div className="space-y-3">
              <div className="flex items-center gap-2 text-sm font-medium text-foreground">
                <Copy className="w-4 h-4 text-primary" />
                Copy Full BRD as Text
              </div>
              <p className="text-[12px] text-muted-foreground leading-relaxed">
                Copies the entire BRD document in Markdown format to your clipboard. Paste into emails, docs, or messaging apps.
              </p>
              <Button
                onClick={handleCopy}
                className="bg-primary text-primary-foreground hover:bg-primary/90 rounded-xl px-6 h-10"
              >
                {copied ? <><Check className="w-4 h-4 mr-2" /> Copied!</> : <><Copy className="w-4 h-4 mr-2" /> Copy to Clipboard</>}
              </Button>
            </div>

            <div className="bg-muted/40 rounded-xl p-4 flex items-start gap-3">
              <Mail className="w-4 h-4 text-muted-foreground mt-0.5 shrink-0" />
              <div>
                <p className="text-[13px] font-medium mb-1">Share via Email</p>
                <p className="text-[12px] text-muted-foreground leading-relaxed">
                  Download the document using one of the export formats, then attach to your email. Real-time collaboration is coming soon.
                </p>
              </div>
            </div>
          </TabsContent>
        </Tabs>

        <DialogFooter className="px-6 py-4 border-t border-border/40 bg-muted/10 flex items-center justify-between sm:justify-between">
          <div className="flex items-center gap-2 text-[12px] text-muted-foreground font-medium">
            <Lock className="w-3.5 h-3.5" />
            Documents are generated locally
          </div>
          <Button onClick={onClose} className="bg-foreground text-background hover:bg-foreground/90 rounded-xl px-6">
            Done
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
